# Path settings
state_dir: ./training_state
out_dir: ./test_out

# Dataset settings
cityscapes_path: ./datasets/cityscapes
kitti_path: ./datasets/kitti
folder_ds_path: ./datasets/test_imgs
webvision_path: ./datasets/webvision
bdd100k_path: ./datasets/bdd100k
flyingchairs_path: ./datasets/flyingchairs
sintel_path: ./datasets/sintel

use_sintel_flow: False

# Select active datasets
use_cityscapes_train: True
use_cityscapes_train_extra: True
use_cityscapes_train_bertha: False
use_cityscapes_val: True
use_cityscapes_test: False
use_bdd100k_train_tracking: False
use_kitti_train: False
use_kitti_val: False
use_kitti_test: False
use_folder_ds: False

# Image size settings
train_image_width: 512
train_image_height: 256
eval_image_width: 1024
eval_image_height: 512
eval_horizontal_fov: 50

# Pretrain settings
pretrain:
  lr_steps: [10000000]
  lr_values: [1.0e-4]
  num_classes: 1000
  batch_size_per_gpu: 8

# Single frame settings
single_frame:
  lr_steps: [1500000, 1750000]
  lr_values: [1.0e-4, 1.0e-5]
  batch_size_per_gpu: 4

# Multi frame settings
multi_frame:
  lr_steps: [1500000, 1750000]
  lr_values: [1.0e-4, 1.0e-5]
  batch_size_per_gpu: 4

# Flow settings
flow:
  lr_steps: [1500000]
  lr_values: [1.0e-4]
  batch_size_per_gpu: 8

# General settings
train_batch_norm: True

# Label settings
train_labels: True
num_label_classes: 19

# Bounding box settings
train_boundingboxes: True
num_bb_classes: 10
boxes_per_pos: 60 # This has to match the target generation code!
box_embedding_len: 32
